export enum EnemyState {
    STATE_PATROL = 0,
    STATE_SENSE,
    STATE_CHASE ,
    STATE_ATTACK ,
    STATE_GET_SMALL_DAMAGE ,
    STATE_GET_BIG_DAMAGE ,
    STATE_DEAD ,
    STATE_VICTORY ,
    STATE_RESPAWN ,
}
